package input

import (
	common "github.com/assemblaj/purego-steamworks"
	"github.com/ebitengine/purego"
)

func init() {
	purego.RegisterLibFunc(&steamInput_init, common.SteamAPIDLL, flatAPI_SteamInput)
	purego.RegisterLibFunc(&iSteamInput_Init, common.SteamAPIDLL, flatAPI_ISteamInput_Init)
	purego.RegisterLibFunc(&iSteamInput_Shutdown, common.SteamAPIDLL, flatAPI_ISteamInput_Shutdown)
	purego.RegisterLibFunc(&iSteamInput_SetInputActionManifestFilePath, common.SteamAPIDLL, flatAPI_ISteamInput_SetInputActionManifestFilePath)
	purego.RegisterLibFunc(&iSteamInput_RunFrame, common.SteamAPIDLL, flatAPI_ISteamInput_RunFrame)
	purego.RegisterLibFunc(&iSteamInput_BWaitForData, common.SteamAPIDLL, flatAPI_ISteamInput_BWaitForData)
	purego.RegisterLibFunc(&iSteamInput_BNewDataAvailable, common.SteamAPIDLL, flatAPI_ISteamInput_BNewDataAvailable)
	purego.RegisterLibFunc(&iSteamInput_GetConnectedControllers, common.SteamAPIDLL, flatAPI_ISteamInput_GetConnectedControllers)
	purego.RegisterLibFunc(&iSteamInput_EnableDeviceCallbacks, common.SteamAPIDLL, flatAPI_ISteamInput_EnableDeviceCallbacks)
	purego.RegisterLibFunc(&iSteamInput_EnableActionEventCallbacks, common.SteamAPIDLL, flatAPI_ISteamInput_EnableActionEventCallbacks)
	purego.RegisterLibFunc(&iSteamInput_GetActionSetHandle, common.SteamAPIDLL, flatAPI_ISteamInput_GetActionSetHandle)
	purego.RegisterLibFunc(&iSteamInput_ActivateActionSet, common.SteamAPIDLL, flatAPI_ISteamInput_ActivateActionSet)
	purego.RegisterLibFunc(&iSteamInput_GetCurrentActionSet, common.SteamAPIDLL, flatAPI_ISteamInput_GetCurrentActionSet)
	purego.RegisterLibFunc(&iSteamInput_ActivateActionSetLayer, common.SteamAPIDLL, flatAPI_ISteamInput_ActivateActionSetLayer)
	purego.RegisterLibFunc(&iSteamInput_DeactivateActionSetLayer, common.SteamAPIDLL, flatAPI_ISteamInput_DeactivateActionSetLayer)
	purego.RegisterLibFunc(&iSteamInput_DeactivateAllActionSetLayers, common.SteamAPIDLL, flatAPI_ISteamInput_DeactivateAllActionSetLayers)
	purego.RegisterLibFunc(&iSteamInput_GetActiveActionSetLayers, common.SteamAPIDLL, flatAPI_ISteamInput_GetActiveActionSetLayers)
	purego.RegisterLibFunc(&iSteamInput_GetDigitalActionHandle, common.SteamAPIDLL, flatAPI_ISteamInput_GetDigitalActionHandle)
	purego.RegisterLibFunc(&iSteamInput_GetDigitalActionData, common.SteamAPIDLL, flatAPI_ISteamInput_GetDigitalActionData)
	purego.RegisterLibFunc(&iSteamInput_GetDigitalActionOrigins, common.SteamAPIDLL, flatAPI_ISteamInput_GetDigitalActionOrigins)
	purego.RegisterLibFunc(&iSteamInput_GetStringForDigitalActionName, common.SteamAPIDLL, flatAPI_ISteamInput_GetStringForDigitalActionName)
	purego.RegisterLibFunc(&iSteamInput_GetAnalogActionHandle, common.SteamAPIDLL, flatAPI_ISteamInput_GetAnalogActionHandle)
	purego.RegisterLibFunc(&iSteamInput_GetAnalogActionData, common.SteamAPIDLL, flatAPI_ISteamInput_GetAnalogActionData)
	purego.RegisterLibFunc(&iSteamInput_GetAnalogActionOrigins, common.SteamAPIDLL, flatAPI_ISteamInput_GetAnalogActionOrigins)
	purego.RegisterLibFunc(&iSteamInput_GetGlyphPNGForActionOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_GetGlyphPNGForActionOrigin)
	purego.RegisterLibFunc(&iSteamInput_GetGlyphSVGForActionOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_GetGlyphSVGForActionOrigin)
	purego.RegisterLibFunc(&iSteamInput_GetGlyphForActionOrigin_Legacy, common.SteamAPIDLL, flatAPI_ISteamInput_GetGlyphForActionOrigin_Legacy)
	purego.RegisterLibFunc(&iSteamInput_GetStringForActionOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_GetStringForActionOrigin)
	purego.RegisterLibFunc(&iSteamInput_GetStringForAnalogActionName, common.SteamAPIDLL, flatAPI_ISteamInput_GetStringForAnalogActionName)
	purego.RegisterLibFunc(&iSteamInput_StopAnalogActionMomentum, common.SteamAPIDLL, flatAPI_ISteamInput_StopAnalogActionMomentum)
	purego.RegisterLibFunc(&iSteamInput_GetMotionData, common.SteamAPIDLL, flatAPI_ISteamInput_GetMotionData)
	purego.RegisterLibFunc(&iSteamInput_TriggerVibration, common.SteamAPIDLL, flatAPI_ISteamInput_TriggerVibration)
	purego.RegisterLibFunc(&iSteamInput_TriggerVibrationExtended, common.SteamAPIDLL, flatAPI_ISteamInput_TriggerVibrationExtended)
	purego.RegisterLibFunc(&iSteamInput_TriggerSimpleHapticEvent, common.SteamAPIDLL, flatAPI_ISteamInput_TriggerSimpleHapticEvent)
	purego.RegisterLibFunc(&iSteamInput_SetLEDColor, common.SteamAPIDLL, flatAPI_ISteamInput_SetLEDColor)
	purego.RegisterLibFunc(&iSteamInput_Legacy_TriggerHapticPulse, common.SteamAPIDLL, flatAPI_ISteamInput_Legacy_TriggerHapticPulse)
	purego.RegisterLibFunc(&iSteamInput_Legacy_TriggerRepeatedHapticPulse, common.SteamAPIDLL, flatAPI_ISteamInput_Legacy_TriggerRepeatedHapticPulse)
	purego.RegisterLibFunc(&iSteamInput_ShowBindingPanel, common.SteamAPIDLL, flatAPI_ISteamInput_ShowBindingPanel)
	purego.RegisterLibFunc(&iSteamInput_GetInputTypeForHandle, common.SteamAPIDLL, flatAPI_ISteamInput_GetInputTypeForHandle)
	purego.RegisterLibFunc(&iSteamInput_GetControllerForGamepadIndex, common.SteamAPIDLL, flatAPI_ISteamInput_GetControllerForGamepadIndex)
	purego.RegisterLibFunc(&iSteamInput_GetGamepadIndexForController, common.SteamAPIDLL, flatAPI_ISteamInput_GetGamepadIndexForController)
	purego.RegisterLibFunc(&iSteamInput_GetStringForXboxOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_GetStringForXboxOrigin)
	purego.RegisterLibFunc(&iSteamInput_GetGlyphForXboxOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_GetGlyphForXboxOrigin)
	purego.RegisterLibFunc(&iSteamInput_GetActionOriginFromXboxOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_GetActionOriginFromXboxOrigin)
	purego.RegisterLibFunc(&iSteamInput_TranslateActionOrigin, common.SteamAPIDLL, flatAPI_ISteamInput_TranslateActionOrigin)
	purego.RegisterLibFunc(&iSteamInput_GetDeviceBindingRevision, common.SteamAPIDLL, flatAPI_ISteamInput_GetDeviceBindingRevision)
	purego.RegisterLibFunc(&iSteamInput_GetRemotePlaySessionID, common.SteamAPIDLL, flatAPI_ISteamInput_GetRemotePlaySessionID)
	purego.RegisterLibFunc(&iSteamInput_GetSessionInputConfigurationSettings, common.SteamAPIDLL, flatAPI_ISteamInput_GetSessionInputConfigurationSettings)
	purego.RegisterLibFunc(&iSteamInput_SetDualSenseTriggerEffect, common.SteamAPIDLL, flatAPI_ISteamInput_SetDualSenseTriggerEffect)
}
