package matchmakingservers

import (
	. "github.com/assemblaj/purego-steamworks"

	"github.com/ebitengine/purego"
)

func init() {
	purego.RegisterLibFunc(&steamMatchmakingServers_init, SteamAPIDLL, flatAPI_SteamMatchmakingServers)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RequestInternetServerList, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RequestInternetServerList)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RequestLANServerList, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RequestLANServerList)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RequestFriendsServerList, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RequestFriendsServerList)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RequestFavoritesServerList, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RequestFavoritesServerList)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RequestHistoryServerList, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RequestHistoryServerList)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RequestSpectatorServerList, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RequestSpectatorServerList)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_ReleaseRequest, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_ReleaseRequest)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_GetServerDetails, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_GetServerDetails)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_CancelQuery, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_CancelQuery)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RefreshQuery, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RefreshQuery)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_IsRefreshing, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_IsRefreshing)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_GetServerCount, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_GetServerCount)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_RefreshServer, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_RefreshServer)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_PingServer, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_PingServer)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_PlayerDetails, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_PlayerDetails)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_ServerRules, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_ServerRules)
	purego.RegisterLibFunc(&iSteamMatchmakingServers_CancelServerQuery, SteamAPIDLL, flatAPI_ISteamMatchmakingServers_CancelServerQuery)
	purego.RegisterLibFunc(&iSteamMatchmakingServerListResponse_ServerResponded, SteamAPIDLL, flatAPI_ISteamMatchmakingServerListResponse_ServerResponded)
	purego.RegisterLibFunc(&iSteamMatchmakingServerListResponse_ServerFailedToRespond, SteamAPIDLL, flatAPI_ISteamMatchmakingServerListResponse_ServerFailedToRespond)
	purego.RegisterLibFunc(&iSteamMatchmakingServerListResponse_RefreshComplete, SteamAPIDLL, flatAPI_ISteamMatchmakingServerListResponse_RefreshComplete)
	purego.RegisterLibFunc(&iSteamMatchmakingPingResponse_ServerResponded, SteamAPIDLL, flatAPI_ISteamMatchmakingPingResponse_ServerResponded)
	purego.RegisterLibFunc(&iSteamMatchmakingPingResponse_ServerFailedToRespond, SteamAPIDLL, flatAPI_ISteamMatchmakingPingResponse_ServerFailedToRespond)
	purego.RegisterLibFunc(&iSteamMatchmakingPlayersResponse_AddPlayerToList, SteamAPIDLL, flatAPI_ISteamMatchmakingPlayersResponse_AddPlayerToList)
	purego.RegisterLibFunc(&iSteamMatchmakingPlayersResponse_PlayersFailedToRespond, SteamAPIDLL, flatAPI_ISteamMatchmakingPlayersResponse_PlayersFailedToRespond)
	purego.RegisterLibFunc(&iSteamMatchmakingPlayersResponse_PlayersRefreshComplete, SteamAPIDLL, flatAPI_ISteamMatchmakingPlayersResponse_PlayersRefreshComplete)
	purego.RegisterLibFunc(&iSteamMatchmakingRulesResponse_RulesResponded, SteamAPIDLL, flatAPI_ISteamMatchmakingRulesResponse_RulesResponded)
	purego.RegisterLibFunc(&iSteamMatchmakingRulesResponse_RulesFailedToRespond, SteamAPIDLL, flatAPI_ISteamMatchmakingRulesResponse_RulesFailedToRespond)
	purego.RegisterLibFunc(&iSteamMatchmakingRulesResponse_RulesRefreshComplete, SteamAPIDLL, flatAPI_ISteamMatchmakingRulesResponse_RulesRefreshComplete)

	purego.RegisterLibFunc(&matchMakingKeyValuePair_t_Construct, SteamAPIDLL, flatAPI_MatchMakingKeyValuePair_t_Construct)

	purego.RegisterLibFunc(&servernetadr_t_Construct, SteamAPIDLL, flatAPI_servernetadr_t_Construct)
	purego.RegisterLibFunc(&servernetadr_t_Init, SteamAPIDLL, flatAPI_servernetadr_t_Init)
	purego.RegisterLibFunc(&servernetadr_t_GetQueryPort, SteamAPIDLL, flatAPI_servernetadr_t_GetQueryPort)
	purego.RegisterLibFunc(&servernetadr_t_SetQueryPort, SteamAPIDLL, flatAPI_servernetadr_t_SetQueryPort)
	purego.RegisterLibFunc(&servernetadr_t_GetConnectionPort, SteamAPIDLL, flatAPI_servernetadr_t_GetConnectionPort)
	purego.RegisterLibFunc(&servernetadr_t_SetConnectionPort, SteamAPIDLL, flatAPI_servernetadr_t_SetConnectionPort)
	purego.RegisterLibFunc(&servernetadr_t_GetIP, SteamAPIDLL, flatAPI_servernetadr_t_GetIP)
	purego.RegisterLibFunc(&servernetadr_t_SetIP, SteamAPIDLL, flatAPI_servernetadr_t_SetIP)
	purego.RegisterLibFunc(&servernetadr_t_GetConnectionAddressString, SteamAPIDLL, flatAPI_servernetadr_t_GetConnectionAddressString)
	purego.RegisterLibFunc(&servernetadr_t_GetQueryAddressString, SteamAPIDLL, flatAPI_servernetadr_t_GetQueryAddressString)
	purego.RegisterLibFunc(&servernetadr_t_IsLessThan, SteamAPIDLL, flatAPI_servernetadr_t_IsLessThan)
	purego.RegisterLibFunc(&servernetadr_t_Assign, SteamAPIDLL, flatAPI_servernetadr_t_Assign)
	purego.RegisterLibFunc(&gameserveritem_t_Construct, SteamAPIDLL, flatAPI_gameserveritem_t_Construct)
	purego.RegisterLibFunc(&gameserveritem_t_GetName, SteamAPIDLL, flatAPI_gameserveritem_t_GetName)
	purego.RegisterLibFunc(&gameserveritem_t_SetName, SteamAPIDLL, flatAPI_gameserveritem_t_SetName)
}
