package networktypes

import (
	. "github.com/assemblaj/purego-steamworks"

	"github.com/ebitengine/purego"
)

func init() {
	purego.RegisterLibFunc(&steamIPAddress_IsSet, SteamAPIDLL, flatAPI_SteamIPAddress_t_IsSet)

	purego.RegisterLibFunc(&steamNetworkingIPAddr_Clear, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_Clear)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_IsIPv6AllZeros, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_IsIPv6AllZeros)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_SetIPv6, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_SetIPv6)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_SetIPv4, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_SetIPv4)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_IsIPv4, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_IsIPv4)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_GetIPv4, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_GetIPv4)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_SetIPv6LocalHost, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_SetIPv6LocalHost)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_IsLocalHost, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_IsLocalHost)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_ToString, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_ToString)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_ParseString, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_ParseString)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_IsEqualTo, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_IsEqualTo)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_GetFakeIPType, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_GetFakeIPType)
	purego.RegisterLibFunc(&steamNetworkingIPAddr_IsFakeIP, SteamAPIDLL, flatAPI_SteamNetworkingIPAddr_IsFakeIP)

	purego.RegisterLibFunc(&steamNetworkingIdentity_Clear, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_Clear)
	purego.RegisterLibFunc(&steamNetworkingIdentity_IsInvalid, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_IsInvalid)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetSteamID, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetSteamID)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetSteamID, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetSteamID)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetSteamID64, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetSteamID64)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetSteamID64, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetSteamID64)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetXboxPairwiseID, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetXboxPairwiseID)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetXboxPairwiseID, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetXboxPairwiseID)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetPSNID, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetPSNID)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetPSNID, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetPSNID)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetIPAddr, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetIPAddr)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetIPAddr, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetIPAddr)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetIPv4Addr, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetIPv4Addr)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetIPv4, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetIPv4)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetFakeIPType, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetFakeIPType)
	purego.RegisterLibFunc(&steamNetworkingIdentity_IsFakeIP, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_IsFakeIP)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetLocalHost, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetLocalHost)
	purego.RegisterLibFunc(&steamNetworkingIdentity_IsLocalHost, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_IsLocalHost)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetGenericString, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetGenericString)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetGenericString, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetGenericString)
	purego.RegisterLibFunc(&steamNetworkingIdentity_SetGenericBytes, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_SetGenericBytes)
	purego.RegisterLibFunc(&steamNetworkingIdentity_GetGenericBytes, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_GetGenericBytes)
	purego.RegisterLibFunc(&steamNetworkingIdentity_IsEqualTo, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_IsEqualTo)
	purego.RegisterLibFunc(&steamNetworkingIdentity_ToString, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_ToString)
	purego.RegisterLibFunc(&steamNetworkingIdentity_ParseString, SteamAPIDLL, flatAPI_SteamNetworkingIdentity_ParseString)

	purego.RegisterLibFunc(&steamNetworkingConfigValue_t_SetInt32, SteamAPIDLL, flatAPI_SteamNetworkingConfigValue_t_SetInt32)
	purego.RegisterLibFunc(&steamNetworkingConfigValue_t_SetInt64, SteamAPIDLL, flatAPI_SteamNetworkingConfigValue_t_SetInt64)
	purego.RegisterLibFunc(&steamNetworkingConfigValue_t_SetFloat, SteamAPIDLL, flatAPI_SteamNetworkingConfigValue_t_SetFloat)
	purego.RegisterLibFunc(&steamNetworkingConfigValue_t_SetPtr, SteamAPIDLL, flatAPI_SteamNetworkingConfigValue_t_SetPtr)
	purego.RegisterLibFunc(&steamNetworkingConfigValue_t_SetString, SteamAPIDLL, flatAPI_SteamNetworkingConfigValue_t_SetString)

	purego.RegisterLibFunc(&steamDatagramHostedAddress_Clear, SteamAPIDLL, flatAPI_SteamDatagramHostedAddress_Clear)
	purego.RegisterLibFunc(&steamDatagramHostedAddress_GetPopID, SteamAPIDLL, flatAPI_SteamDatagramHostedAddress_GetPopID)
	purego.RegisterLibFunc(&steamDatagramHostedAddress_SetDevAddress, SteamAPIDLL, flatAPI_SteamDatagramHostedAddress_SetDevAddress)

	purego.RegisterLibFunc(&iSteamNetworkingFakeUDPPort_DestroyFakeUDPPort, SteamAPIDLL, flatAPI_ISteamNetworkingFakeUDPPort_DestroyFakeUDPPort)
	purego.RegisterLibFunc(&iSteamNetworkingFakeUDPPort_SendMessageToFakeIP, SteamAPIDLL, flatAPI_ISteamNetworkingFakeUDPPort_SendMessageToFakeIP)
	purego.RegisterLibFunc(&iSteamNetworkingFakeUDPPort_ReceiveMessages, SteamAPIDLL, flatAPI_ISteamNetworkingFakeUDPPort_ReceiveMessages)
	purego.RegisterLibFunc(&iSteamNetworkingFakeUDPPort_ScheduleCleanup, SteamAPIDLL, flatAPI_ISteamNetworkingFakeUDPPort_ScheduleCleanup)

}
