package matchmaking

import (
	"sync"

	. "github.com/assemblaj/purego-steamworks"

	"github.com/ebitengine/purego"
)

var once sync.Once

func init() {
	purego.RegisterLibFunc(&steamMatchmaking_init, SteamAPIDLL, flatAPI_SteamMatchmaking)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetFavoriteGameCount, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetFavoriteGameCount)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetFavoriteGame, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetFavoriteGame)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddFavoriteGame, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddFavoriteGame)
	purego.RegisterLibFunc(&iSteamMatchmaking_RemoveFavoriteGame, SteamAPIDLL, flatAPI_ISteamMatchmaking_RemoveFavoriteGame)
	purego.RegisterLibFunc(&iSteamMatchmaking_RequestLobbyList, SteamAPIDLL, flatAPI_ISteamMatchmaking_RequestLobbyList)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListStringFilter, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListStringFilter)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListNumericalFilter, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListNumericalFilter)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListNearValueFilter, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListNearValueFilter)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListDistanceFilter, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListDistanceFilter)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListResultCountFilter, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListResultCountFilter)
	purego.RegisterLibFunc(&iSteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter, SteamAPIDLL, flatAPI_ISteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyByIndex, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyByIndex)
	purego.RegisterLibFunc(&iSteamMatchmaking_CreateLobby, SteamAPIDLL, flatAPI_ISteamMatchmaking_CreateLobby)
	purego.RegisterLibFunc(&iSteamMatchmaking_JoinLobby, SteamAPIDLL, flatAPI_ISteamMatchmaking_JoinLobby)
	purego.RegisterLibFunc(&iSteamMatchmaking_LeaveLobby, SteamAPIDLL, flatAPI_ISteamMatchmaking_LeaveLobby)
	purego.RegisterLibFunc(&iSteamMatchmaking_InviteUserToLobby, SteamAPIDLL, flatAPI_ISteamMatchmaking_InviteUserToLobby)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetNumLobbyMembers, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetNumLobbyMembers)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyMemberByIndex, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyMemberByIndex)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyData, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyData)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyData, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyData)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyDataCount, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyDataCount)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyDataByIndex, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyDataByIndex)
	purego.RegisterLibFunc(&iSteamMatchmaking_DeleteLobbyData, SteamAPIDLL, flatAPI_ISteamMatchmaking_DeleteLobbyData)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyMemberData, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyMemberData)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyMemberData, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyMemberData)
	purego.RegisterLibFunc(&iSteamMatchmaking_SendLobbyChatMsg, SteamAPIDLL, flatAPI_ISteamMatchmaking_SendLobbyChatMsg)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyChatEntry, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyChatEntry)
	purego.RegisterLibFunc(&iSteamMatchmaking_RequestLobbyData, SteamAPIDLL, flatAPI_ISteamMatchmaking_RequestLobbyData)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyGameServer, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyGameServer)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyGameServer, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyGameServer)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyMemberLimit, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyMemberLimit)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyMemberLimit, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyMemberLimit)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyType, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyType)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyJoinable, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyJoinable)
	purego.RegisterLibFunc(&iSteamMatchmaking_GetLobbyOwner, SteamAPIDLL, flatAPI_ISteamMatchmaking_GetLobbyOwner)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLobbyOwner, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLobbyOwner)
	purego.RegisterLibFunc(&iSteamMatchmaking_SetLinkedLobby, SteamAPIDLL, flatAPI_ISteamMatchmaking_SetLinkedLobby)
}
