package userstats

import (
	"sync"

	. "github.com/assemblaj/purego-steamworks"

	"github.com/ebitengine/purego"
)

var once sync.Once

func init() {
	purego.RegisterLibFunc(&steamUserStats_init, SteamAPIDLL, flatAPI_SteamUserStats)
	purego.RegisterLibFunc(&iSteamUserStats_GetStatInt32, SteamAPIDLL, flatAPI_ISteamUserStats_GetStatInt32)
	purego.RegisterLibFunc(&iSteamUserStats_GetStatFloat, SteamAPIDLL, flatAPI_ISteamUserStats_GetStatFloat)
	purego.RegisterLibFunc(&iSteamUserStats_SetStatInt32, SteamAPIDLL, flatAPI_ISteamUserStats_SetStatInt32)
	purego.RegisterLibFunc(&iSteamUserStats_SetStatFloat, SteamAPIDLL, flatAPI_ISteamUserStats_SetStatFloat)
	purego.RegisterLibFunc(&iSteamUserStats_UpdateAvgRateStat, SteamAPIDLL, flatAPI_ISteamUserStats_UpdateAvgRateStat)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievement, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievement)
	purego.RegisterLibFunc(&iSteamUserStats_SetAchievement, SteamAPIDLL, flatAPI_ISteamUserStats_SetAchievement)
	purego.RegisterLibFunc(&iSteamUserStats_ClearAchievement, SteamAPIDLL, flatAPI_ISteamUserStats_ClearAchievement)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementAndUnlockTime, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementAndUnlockTime)
	purego.RegisterLibFunc(&iSteamUserStats_StoreStats, SteamAPIDLL, flatAPI_ISteamUserStats_StoreStats)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementIcon, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementIcon)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementDisplayAttribute, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementDisplayAttribute)
	purego.RegisterLibFunc(&iSteamUserStats_IndicateAchievementProgress, SteamAPIDLL, flatAPI_ISteamUserStats_IndicateAchievementProgress)
	purego.RegisterLibFunc(&iSteamUserStats_GetNumAchievements, SteamAPIDLL, flatAPI_ISteamUserStats_GetNumAchievements)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementName, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementName)
	purego.RegisterLibFunc(&iSteamUserStats_RequestUserStats, SteamAPIDLL, flatAPI_ISteamUserStats_RequestUserStats)
	purego.RegisterLibFunc(&iSteamUserStats_GetUserStatInt32, SteamAPIDLL, flatAPI_ISteamUserStats_GetUserStatInt32)
	purego.RegisterLibFunc(&iSteamUserStats_GetUserStatFloat, SteamAPIDLL, flatAPI_ISteamUserStats_GetUserStatFloat)
	purego.RegisterLibFunc(&iSteamUserStats_GetUserAchievement, SteamAPIDLL, flatAPI_ISteamUserStats_GetUserAchievement)
	purego.RegisterLibFunc(&iSteamUserStats_GetUserAchievementAndUnlockTime, SteamAPIDLL, flatAPI_ISteamUserStats_GetUserAchievementAndUnlockTime)
	purego.RegisterLibFunc(&iSteamUserStats_ResetAllStats, SteamAPIDLL, flatAPI_ISteamUserStats_ResetAllStats)
	purego.RegisterLibFunc(&iSteamUserStats_FindOrCreateLeaderboard, SteamAPIDLL, flatAPI_ISteamUserStats_FindOrCreateLeaderboard)
	purego.RegisterLibFunc(&iSteamUserStats_FindLeaderboard, SteamAPIDLL, flatAPI_ISteamUserStats_FindLeaderboard)
	purego.RegisterLibFunc(&iSteamUserStats_GetLeaderboardName, SteamAPIDLL, flatAPI_ISteamUserStats_GetLeaderboardName)
	purego.RegisterLibFunc(&iSteamUserStats_GetLeaderboardEntryCount, SteamAPIDLL, flatAPI_ISteamUserStats_GetLeaderboardEntryCount)
	purego.RegisterLibFunc(&iSteamUserStats_GetLeaderboardSortMethod, SteamAPIDLL, flatAPI_ISteamUserStats_GetLeaderboardSortMethod)
	purego.RegisterLibFunc(&iSteamUserStats_GetLeaderboardDisplayType, SteamAPIDLL, flatAPI_ISteamUserStats_GetLeaderboardDisplayType)
	purego.RegisterLibFunc(&iSteamUserStats_DownloadLeaderboardEntries, SteamAPIDLL, flatAPI_ISteamUserStats_DownloadLeaderboardEntries)
	purego.RegisterLibFunc(&iSteamUserStats_DownloadLeaderboardEntriesForUsers, SteamAPIDLL, flatAPI_ISteamUserStats_DownloadLeaderboardEntriesForUsers)
	purego.RegisterLibFunc(&iSteamUserStats_GetDownloadedLeaderboardEntry, SteamAPIDLL, flatAPI_ISteamUserStats_GetDownloadedLeaderboardEntry)
	purego.RegisterLibFunc(&iSteamUserStats_UploadLeaderboardScore, SteamAPIDLL, flatAPI_ISteamUserStats_UploadLeaderboardScore)
	purego.RegisterLibFunc(&iSteamUserStats_AttachLeaderboardUGC, SteamAPIDLL, flatAPI_ISteamUserStats_AttachLeaderboardUGC)
	purego.RegisterLibFunc(&iSteamUserStats_GetNumberOfCurrentPlayers, SteamAPIDLL, flatAPI_ISteamUserStats_GetNumberOfCurrentPlayers)
	purego.RegisterLibFunc(&iSteamUserStats_RequestGlobalAchievementPercentages, SteamAPIDLL, flatAPI_ISteamUserStats_RequestGlobalAchievementPercentages)
	purego.RegisterLibFunc(&iSteamUserStats_GetMostAchievedAchievementInfo, SteamAPIDLL, flatAPI_ISteamUserStats_GetMostAchievedAchievementInfo)
	purego.RegisterLibFunc(&iSteamUserStats_GetNextMostAchievedAchievementInfo, SteamAPIDLL, flatAPI_ISteamUserStats_GetNextMostAchievedAchievementInfo)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementAchievedPercent, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementAchievedPercent)
	purego.RegisterLibFunc(&iSteamUserStats_RequestGlobalStats, SteamAPIDLL, flatAPI_ISteamUserStats_RequestGlobalStats)
	purego.RegisterLibFunc(&iSteamUserStats_GetGlobalStatInt64, SteamAPIDLL, flatAPI_ISteamUserStats_GetGlobalStatInt64)
	purego.RegisterLibFunc(&iSteamUserStats_GetGlobalStatDouble, SteamAPIDLL, flatAPI_ISteamUserStats_GetGlobalStatDouble)
	purego.RegisterLibFunc(&iSteamUserStats_GetGlobalStatHistoryInt64, SteamAPIDLL, flatAPI_ISteamUserStats_GetGlobalStatHistoryInt64)
	purego.RegisterLibFunc(&iSteamUserStats_GetGlobalStatHistoryDouble, SteamAPIDLL, flatAPI_ISteamUserStats_GetGlobalStatHistoryDouble)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementProgressLimitsInt32, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementProgressLimitsInt32)
	purego.RegisterLibFunc(&iSteamUserStats_GetAchievementProgressLimitsFloat, SteamAPIDLL, flatAPI_ISteamUserStats_GetAchievementProgressLimitsFloat)

	steamUserStats = steamUserStats_init()
}
